######################################################################
# Automatically generated by qmake (2.01a) Sat Apr 21 11:01:25 2012
######################################################################

TEMPLATE = app
TARGET = newMakefiles
DESTDIR = ../../bin

SOURCES += main.cpp

