######################################################################
# Automatically generated by qmake (2.01a) dim. oct. 21 16:49:57 2012
######################################################################

INCLUDEPATH += $${PWD}

# Input
HEADERS += $${PWD}/findreceiptsvalues.h \
           $${PWD}/constants.h \
           $${PWD}/receipstools.h
FORMS +=   $${PWD}/findvaluesgui.ui
SOURCES += $${PWD}/findreceiptsvalues.cpp \
           $${PWD}/receipstools.cpp
