
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;


CREATE TABLE IF NOT EXISTS "ACCES1" (
  "CODE" char(1) NOT NULL DEFAULT '',
  "ACCES" varchar(80) DEFAULT NULL,
  "LIBELLE" varchar(255) DEFAULT NULL,
  PRIMARY KEY ("CODE"),
  KEY "ACCES" ("ACCES")
);

CREATE TABLE IF NOT EXISTS "ACCES2" (
  "PERE" char(1) DEFAULT NULL,
  "LIBELLE" varchar(150) DEFAULT NULL,
  KEY "PERE" ("PERE")
);

CREATE TABLE IF NOT EXISTS "ACTES" (
  "CODE" varchar(13) NOT NULL DEFAULT '',
  "LIBELLECOURT" varchar(70) DEFAULT NULL,
  "TYPE" char(1) DEFAULT NULL,
  "SEXE" char(1) DEFAULT NULL,
  "DATECREATION" varchar(8) DEFAULT NULL,
  "DATEFIN" varchar(8) DEFAULT NULL,
  "ASSURANCE1" char(2) DEFAULT NULL,
  "ASSURANCE2" char(2) DEFAULT NULL,
  "ASSURANCE3" char(2) DEFAULT NULL,
  "ASSURANCE4" char(2) DEFAULT NULL,
  "ASSURANCE5" char(2) DEFAULT NULL,
  "ASSURANCE6" char(2) DEFAULT NULL,
  "ASSURANCE7" char(2) DEFAULT NULL,
  "ASSURANCE8" char(2) DEFAULT NULL,
  "ASSURANCE9" char(2) DEFAULT NULL,
  "ASSURANCE10" char(2) DEFAULT NULL,
  "DEPLACEMENT" char(1) DEFAULT NULL,
  "ARBORESCENCE1" varchar(6) DEFAULT NULL,
  "ARBORESCENCE2" varchar(6) DEFAULT NULL,
  "ARBORESCENCE3" varchar(6) DEFAULT NULL,
  "ARBORESCENCE4" varchar(6) DEFAULT NULL,
  "ARBORESCENCE5" varchar(6) DEFAULT NULL,
  "ARBORESCENCE6" varchar(6) DEFAULT NULL,
  "ARBORESCENCE7" varchar(6) DEFAULT NULL,
  "ARBORESCENCE8" varchar(6) DEFAULT NULL,
  "ARBORESCENCE9" varchar(6) DEFAULT NULL,
  "ARBORESCENCE10" varchar(6) DEFAULT NULL,
  "PLACEARBORESCENCE" varchar(12) DEFAULT NULL,
  "CODESTRUCTURE" varchar(13) DEFAULT NULL,
  "CODEPRECEDENT" varchar(13) DEFAULT NULL,
  "CODESUIVANT" varchar(13) DEFAULT NULL,
  "LIBELLELONG" text,
  "CCAM26" varchar(8) DEFAULT NULL,
  "CCAM27" varchar(8) DEFAULT NULL,
  "CCAM28" varchar(8) DEFAULT NULL,
  "CCAM22" char(1) DEFAULT NULL,
  "CCAM24" char(1) DEFAULT NULL,
  "CCAM25" varchar(5) DEFAULT NULL,
  "CCAM31" varchar(20) DEFAULT NULL,
  "CCAM34" varchar(10) DEFAULT NULL,
  PRIMARY KEY ("CODE")
);

CREATE TABLE IF NOT EXISTS "ACTION1" (
  "VERBE" varchar(20) NOT NULL DEFAULT '',
  "CODE" char(1) DEFAULT NULL,
  "LIBELLE" varchar(255) DEFAULT NULL,
  PRIMARY KEY ("VERBE"),
  KEY "CODE" ("CODE")
);

CREATE TABLE IF NOT EXISTS "ACTION2" (
  "VERBE" varchar(30) DEFAULT NULL,
  "CODE" char(1) DEFAULT NULL,
  "SUBSTANTIF" varchar(20) DEFAULT NULL,
  KEY "ACTION" ("VERBE"),
  KEY "CODE" ("CODE"),
  KEY "VERBE" ("SUBSTANTIF")
);

CREATE TABLE IF NOT EXISTS "ACTIVITE" (
  "CODE" char(1) NOT NULL DEFAULT '',
  "LIBELLE" varchar(100) DEFAULT NULL,
  PRIMARY KEY ("CODE")
);

CREATE TABLE IF NOT EXISTS "ACTIVITEACTE" (
  "CODEACTE" char(13) DEFAULT NULL,
  "ACTIVITE" char(1) DEFAULT NULL,
  KEY "CODEACTE" ("CODEACTE"),
  KEY "ACTIVITE" ("ACTIVITE")
);

CREATE TABLE IF NOT EXISTS "ADM_REMB" (
  "CODE" char(1) NOT NULL DEFAULT '',
  "LIBELLE" varchar(80) DEFAULT NULL,
  PRIMARY KEY ("CODE")
);

CREATE TABLE IF NOT EXISTS "AGR_RADIO" (
  "CODE" char(2) NOT NULL DEFAULT '',
  "LIBELLE" varchar(100) DEFAULT NULL,
  PRIMARY KEY ("CODE")
);

CREATE TABLE IF NOT EXISTS "ARBORESCENCE" (
  "CODEMENU" varchar(6) NOT NULL DEFAULT '',
  "CODEPERE" varchar(6) DEFAULT NULL,
  "RANG" varchar(6) DEFAULT NULL,
  "LIBELLE" text,
  PRIMARY KEY ("CODEMENU"),
  KEY "CODEPERE" ("CODEPERE"),
  KEY "RANG" ("RANG")
);

CREATE TABLE IF NOT EXISTS "ASSOCIABILITE" (
  "CODEACTE" char(13) DEFAULT NULL,
  "ACTIVITE" char(1) DEFAULT NULL,
  "DATEEFFET" char(8) DEFAULT NULL,
  "ACTEASSO" char(13) DEFAULT NULL,
  "ACTIVITEASSO" char(1) DEFAULT NULL,
  "REGLE" char(1) DEFAULT NULL,
  KEY "CODEACTE" ("CODEACTE"),
  KEY "ACTIVITE" ("ACTIVITE")
);

CREATE TABLE IF NOT EXISTS "ASSOCIATION" (
  "CODE" char(1) NOT NULL DEFAULT '',
  "DATEDEBUT" char(8) DEFAULT NULL,
  "DATEFIN" char(8) DEFAULT NULL,
  "COEFFICIENT" decimal(4,3) DEFAULT NULL,
  PRIMARY KEY ("CODE")
);

CREATE TABLE IF NOT EXISTS "ASS_NPREV" (
  "CODE" char(1) NOT NULL DEFAULT '',
  "LIBELLE" varchar(100) DEFAULT NULL,
  PRIMARY KEY ("CODE")
);

CREATE TABLE IF NOT EXISTS "CAT_MED" (
  "CODE" char(2) NOT NULL DEFAULT '',
  "LIBELLE" varchar(100) DEFAULT NULL,
  PRIMARY KEY ("CODE")
);

CREATE TABLE IF NOT EXISTS "CAT_SPEC" (
  "CODE" char(2) NOT NULL DEFAULT '',
  "LIBELLE" varchar(100) DEFAULT NULL,
  PRIMARY KEY ("CODE")
);

CREATE TABLE IF NOT EXISTS "CLASSE_DMT" (
  "CODE" char(2) NOT NULL DEFAULT '',
  "LIBELLE" varchar(100) DEFAULT NULL,
  PRIMARY KEY ("CODE")
);

CREATE TABLE IF NOT EXISTS "CODE_PAIEMENT" (
  "CODE" char(1) NOT NULL DEFAULT '',
  "LIBELLE" varchar(80) DEFAULT NULL,
  PRIMARY KEY ("CODE")
);

CREATE TABLE IF NOT EXISTS "COD_REGROUP" (
  "CODE" char(3) NOT NULL DEFAULT '',
  "LIBELLE" varchar(100) DEFAULT NULL,
  PRIMARY KEY ("CODE")
);

CREATE TABLE IF NOT EXISTS "COMPAT_EXO_TM" (
  "EXOTM" char(1) NOT NULL DEFAULT '',
  "EXOTMCOMPAT" char(1) NOT NULL DEFAULT '',
  PRIMARY KEY ("EXOTM")
);

CREATE TABLE IF NOT EXISTS "COND_GEN" (
  "CODE" varchar(4) NOT NULL DEFAULT '',
  "LIBELLE" varchar(100) DEFAULT NULL,
  PRIMARY KEY ("CODE")
);

CREATE TABLE IF NOT EXISTS "COND_GEN_ACTE" (
  "ACTE" varchar(13) DEFAULT NULL,
  "CONDITION" varchar(4) DEFAULT NULL,
  KEY "ACTE" ("ACTE"),
  KEY "CONDITION" ("CONDITION")
);

CREATE TABLE IF NOT EXISTS "DATES_EFFET" (
  "DATE_EFFET" char(8) DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS "DMT" (
  "CODE" char(3) NOT NULL DEFAULT '',
  "LIBELLE" varchar(100) DEFAULT NULL,
  PRIMARY KEY ("CODE")
);

CREATE TABLE IF NOT EXISTS "DOM" (
  "CODE" char(3) NOT NULL DEFAULT '',
  "LIBELLE" varchar(50) DEFAULT NULL,
  PRIMARY KEY ("CODE")
);

CREATE TABLE IF NOT EXISTS "EXO_TM" (
  "CODE" char(1) NOT NULL DEFAULT '',
  "LIBELLE" varchar(80) DEFAULT NULL,
  PRIMARY KEY ("CODE")
);

CREATE TABLE IF NOT EXISTS "EXT_DOC" (
  "CODE" char(1) NOT NULL DEFAULT '',
  "LIBELLE" varchar(100) DEFAULT NULL,
  PRIMARY KEY ("CODE")
);

CREATE TABLE IF NOT EXISTS "FRAIS_DEP" (
  "CODE" char(1) NOT NULL DEFAULT '',
  "LIBELLE" varchar(80) DEFAULT NULL,
  PRIMARY KEY ("CODE")
);

CREATE TABLE IF NOT EXISTS "HISTO_PHASE" (
  "CODEACTE" varchar(13) DEFAULT NULL,
  "ACTIVITE" char(1) DEFAULT NULL,
  "PHASE" char(1) DEFAULT NULL,
  "DATE_EFFET" varchar(8) DEFAULT NULL,
  "DATE_AM" varchar(8) DEFAULT NULL,
  "DATE_JO" varchar(8) DEFAULT NULL,
  "NBMAX" int(2) DEFAULT NULL,
  "UO" char(3) DEFAULT NULL,
  "COEF_UO" decimal(6,2) DEFAULT NULL,
  "CODEPAIEMENT" char(1) DEFAULT NULL,
  "PU" decimal(6,2) DEFAULT NULL,
  "MAJDOM1" decimal(4,3) DEFAULT NULL,
  "MAJDOM2" decimal(4,3) DEFAULT NULL,
  "MAJDOM3" decimal(4,3) DEFAULT NULL,
  "MAJDOM4" decimal(4,3) DEFAULT NULL,
  "SUPP_CHG" decimal(6,2) DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS "INCOMPATIBILITE" (
  "CODEACTE" char(13) DEFAULT NULL,
  "DATEEFFET" char(8) DEFAULT NULL,
  "INCOMPATIBLE" char(13) DEFAULT NULL,
  KEY "CODEACTE" ("CODEACTE")
);

CREATE TABLE IF NOT EXISTS "LISTE_MOTS" (
  "MOT" varchar(50) DEFAULT NULL,
  "DEFINITION" text,
  KEY "MOT" ("MOT")
);

CREATE TABLE IF NOT EXISTS "MEDECINS" (
  "CODE" char(6) NOT NULL DEFAULT '',
  "PWD" char(32) DEFAULT NULL,
  "NOM" char(30) DEFAULT NULL,
  "PRENOM" char(30) DEFAULT NULL,
  "NID" char(9) DEFAULT NULL,
  "SPEC" char(2) DEFAULT NULL,
  PRIMARY KEY ("CODE")
);

CREATE TABLE IF NOT EXISTS "MODIFICATEUR" (
  "CODE" char(1) NOT NULL DEFAULT '',
  "LIBELLE" varchar(100) DEFAULT NULL,
  PRIMARY KEY ("CODE")
);

CREATE TABLE IF NOT EXISTS "MODIFICATEURACTE" (
  "CODEACTE" varchar(13) DEFAULT NULL,
  "CODEACTIVITE" char(1) DEFAULT NULL,
  "DATEEFFET" varchar(8) DEFAULT NULL,
  "MODIFICATEUR" char(1) DEFAULT NULL,
  KEY "CODEACTE" ("CODEACTE"),
  KEY "CODEACTIVITE" ("CODEACTIVITE"),
  KEY "MODIFICATEUR" ("MODIFICATEUR")
);

CREATE TABLE IF NOT EXISTS "NAT_ASS" (
  "CODE" char(2) NOT NULL DEFAULT '',
  "LIBELLE" varchar(100) DEFAULT NULL,
  PRIMARY KEY ("CODE")
);

CREATE TABLE IF NOT EXISTS "NOTES" (
  "CODEACTE" varchar(13) DEFAULT NULL,
  "TYPE" char(2) DEFAULT NULL,
  "TEXTE" text,
  KEY "CODEACTE" ("CODEACTE"),
  KEY "TYPE" ("TYPE")
);

CREATE TABLE IF NOT EXISTS "NOTESARBORESCENCE" (
  "CODEMENU" varchar(6) DEFAULT NULL,
  "TYPE" char(2) DEFAULT NULL,
  "TEXTE" text,
  KEY "CODEMENU" ("CODEMENU")
);

CREATE TABLE IF NOT EXISTS "NUM_DENTS" (
  "CODE" char(2) NOT NULL DEFAULT '',
  "LIBELLE" varchar(80) DEFAULT NULL,
  PRIMARY KEY ("CODE")
);

CREATE TABLE IF NOT EXISTS "PHASE" (
  "CODE" char(1) NOT NULL DEFAULT '',
  "LIBELLE" varchar(80) DEFAULT NULL,
  PRIMARY KEY ("CODE")
);

CREATE TABLE IF NOT EXISTS "PHASEACTE" (
  "CODEACTE" char(13) DEFAULT NULL,
  "ACTIVITE" char(1) DEFAULT NULL,
  "PHASE" char(1) DEFAULT NULL,
  "NBDENTS" char(2) DEFAULT NULL,
  "AGEMINI" char(3) DEFAULT NULL,
  "AGEMAXI" char(3) DEFAULT NULL,
  "ICR" char(4) DEFAULT NULL,
  "CLASSANT" char(1) DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS "PROCEDURES" (
  "CODEACTE" char(13) DEFAULT NULL,
  "DATEEFFET" char(8) DEFAULT NULL,
  "CODEPROCEDURE" char(13) DEFAULT NULL,
  KEY "CODEACTE" ("CODEACTE")
);

CREATE TABLE IF NOT EXISTS "REC_MED_ACTE" (
  "ACTE" varchar(13) DEFAULT NULL,
  "ACTIVITE" char(1) DEFAULT NULL,
  "RECMED" varchar(5) DEFAULT NULL,
  "TEXTE" text,
  KEY "ACTE" ("ACTE"),
  KEY "ACTIVITE" ("ACTIVITE"),
  KEY "RECMED" ("RECMED")
);

CREATE TABLE IF NOT EXISTS "RGL_TARIF" (
  "CODE" char(1) NOT NULL DEFAULT '',
  "LIBELLE" varchar(100) DEFAULT NULL,
  PRIMARY KEY ("CODE")
);

CREATE TABLE IF NOT EXISTS "SPECIALITES" (
  "CODE" char(2) NOT NULL DEFAULT '',
  "LIBELLE" varchar(100) DEFAULT NULL,
  PRIMARY KEY ("CODE")
);

CREATE TABLE IF NOT EXISTS "TB03" (
  "REGLE" char(1) NOT NULL DEFAULT '',
  "DATEDEBUT" char(8) DEFAULT NULL,
  "DATEFIN" char(8) DEFAULT NULL,
  "COEFFICIENT" decimal(4,3) DEFAULT NULL,
  PRIMARY KEY ("REGLE")
);

CREATE TABLE IF NOT EXISTS "TB04" (
  "SPECIALITE" char(2) NOT NULL DEFAULT '',
  "DATEDEBUT" char(8) DEFAULT NULL,
  "DATEFIN" char(8) DEFAULT NULL,
  "CLASSE_SPECIALITE" char(2) DEFAULT NULL,
  KEY "SPECIALITE" ("SPECIALITE")
);

CREATE TABLE IF NOT EXISTS "TB05" (
  "NAT_PRESTATION" char(3) NOT NULL DEFAULT '',
  "DATEDEBUT" char(8) DEFAULT NULL,
  "DATEFIN" char(8) DEFAULT NULL,
  "TYPE_FORFAIT" char(1) DEFAULT NULL,
  KEY "NAT_PRESTATION" ("NAT_PRESTATION")
);

CREATE TABLE IF NOT EXISTS "TB06" (
  "CODE_MODIF" char(1) NOT NULL DEFAULT '',
  "DATEDEBUT" char(8) DEFAULT NULL,
  "DATEFIN" char(8) DEFAULT NULL,
  "UNITE_AGEMINI" char(1) DEFAULT NULL,
  "AGEMINI" int(3) DEFAULT NULL,
  "UNITE_AGEMAXI" char(1) DEFAULT NULL,
  "AGEMAXI" int(3) DEFAULT NULL,
  KEY "CODE_MODIF" ("CODE_MODIF")
);

CREATE TABLE IF NOT EXISTS "TB07" (
  "SERIE" int(11) NOT NULL,
  "DATEDEBUT" char(8) DEFAULT NULL,
  "DATEFIN" char(8) DEFAULT NULL,
  "SEUIL_MET" decimal(7,2) DEFAULT NULL,
  "SEUIL_ANT" decimal(7,2) DEFAULT NULL,
  "SEUIL_REU" decimal(7,2) DEFAULT NULL,
  "SEUIL_GUY" decimal(7,2) DEFAULT NULL,
  PRIMARY KEY ("SERIE")
);

CREATE TABLE IF NOT EXISTS "TB08" (
  "SERIE" int(11) NOT NULL,
  "CAISSE" char(3) DEFAULT NULL,
  "DATEDEBUT" char(8) DEFAULT NULL,
  "DATEFIN" char(8) DEFAULT NULL,
  "TYPE_FERIE" char(1) DEFAULT NULL,
  "JOUR" char(8) DEFAULT NULL,
  PRIMARY KEY ("SERIE")
);

CREATE TABLE IF NOT EXISTS "TB09" (
  "SERIE" int(11) NOT NULL,
  "MODIFICATEUR" char(1) DEFAULT NULL,
  "COMPATIBLE" char(1) DEFAULT NULL,
  "DATEDEBUT" char(8) DEFAULT NULL,
  "DATEFIN" char(8) DEFAULT NULL,
  PRIMARY KEY ("SERIE")
);

CREATE TABLE IF NOT EXISTS "TB10" (
  "SERIE" int(11) NOT NULL,
  "MODIFICATEUR" char(1) DEFAULT NULL,
  "DATEDEBUT" char(8) DEFAULT NULL,
  "DATEFIN" char(8) DEFAULT NULL,
  "COHERENCE" char(1) DEFAULT NULL,
  "PRES_MULTIPLE" char(1) DEFAULT NULL,
  PRIMARY KEY ("SERIE")
);

CREATE TABLE IF NOT EXISTS "TB11" (
  "SERIE" int(11) NOT NULL,
  "MODIFICATEUR" char(1) DEFAULT NULL,
  "DATEDEBUT" char(8) DEFAULT NULL,
  "DATEFIN" char(8) DEFAULT NULL,
  "FORFAIT" decimal(7,2) DEFAULT NULL,
  "COEF" decimal(4,3) DEFAULT NULL,
  PRIMARY KEY ("SERIE")
);

CREATE TABLE IF NOT EXISTS "TB12" (
  "SERIE" int(11) NOT NULL,
  "DATEDEBUT" char(8) DEFAULT NULL,
  "DATEFIN" char(8) DEFAULT NULL,
  "FORFAIT" decimal(7,2) DEFAULT NULL,
  "COEF" decimal(4,3) DEFAULT NULL,
  PRIMARY KEY ("SERIE")
);

CREATE TABLE IF NOT EXISTS "TB13" (
  "SERIE" int(11) NOT NULL,
  "PRESTATION" char(3) DEFAULT NULL,
  "DATEDEBUT" char(8) DEFAULT NULL,
  "DATEFIN" char(8) DEFAULT NULL,
  "EQUIVAL" char(1) DEFAULT NULL,
  PRIMARY KEY ("SERIE")
);

CREATE TABLE IF NOT EXISTS "TB14" (
  "SERIE" int(11) NOT NULL,
  "DMT" char(3) DEFAULT NULL,
  "DATEDEBUT" char(8) DEFAULT NULL,
  "DATEFIN" char(8) DEFAULT NULL,
  "CLASSE_DMT" char(2) DEFAULT NULL,
  PRIMARY KEY ("SERIE")
);

CREATE TABLE IF NOT EXISTS "TB15" (
  "SERIE" int(11) NOT NULL,
  "MODIFICATEUR" char(1) DEFAULT NULL,
  "DATEDEBUT" char(8) DEFAULT NULL,
  "DATEFIN" char(8) DEFAULT NULL,
  "MODIF_OC" char(1) DEFAULT NULL,
  PRIMARY KEY ("SERIE")
);

CREATE TABLE IF NOT EXISTS "TB17" (
  "SERIE" int(11) NOT NULL,
  "PRESTATION" char(3) DEFAULT NULL,
  "SPECIALITE" char(2) DEFAULT NULL,
  "DATE_OBLIG" char(8) DEFAULT NULL,
  PRIMARY KEY ("SERIE")
);

CREATE TABLE IF NOT EXISTS "TB18" (
  "SERIE" int(11) NOT NULL,
  "DATEDEBUT" char(8) DEFAULT NULL,
  "DATEFIN" char(8) DEFAULT NULL,
  "LOCALISATION" char(2) DEFAULT NULL,
  PRIMARY KEY ("SERIE")
);

CREATE TABLE IF NOT EXISTS "TB19" (
  "SERIE" int(11) NOT NULL,
  "DATEDEBUT" char(8) DEFAULT NULL,
  "DATEFIN" char(8) DEFAULT NULL,
  "NB_MODIF" int(3) DEFAULT NULL,
  PRIMARY KEY ("SERIE")
);

CREATE TABLE IF NOT EXISTS "TB20" (
  "SERIE" int(11) NOT NULL,
  "CONCEPT" char(2) DEFAULT NULL,
  "DATEDEBUT" char(8) DEFAULT NULL,
  "DATEFIN" char(8) DEFAULT NULL,
  "VALEUR" char(10) DEFAULT NULL,
  PRIMARY KEY ("SERIE")
);

CREATE TABLE IF NOT EXISTS "THESAURUS" (
  "SERIE" int(11) NOT NULL,
  "CODEMEDECIN" char(64) DEFAULT NULL,
  "CATEGORIE" char(40) DEFAULT NULL,
  "LIBUSUEL" char(50) DEFAULT NULL,
  "CODEACTE" char(13) DEFAULT NULL,
  PRIMARY KEY ("SERIE"),
  KEY "CODEMEDECIN" ("CODEMEDECIN")
);

CREATE TABLE IF NOT EXISTS "TOPOGRAPHIE1" (
  "CODE" char(1) NOT NULL DEFAULT '',
  "LIBELLE" varchar(80) DEFAULT NULL,
  PRIMARY KEY ("CODE")
);

CREATE TABLE IF NOT EXISTS "TOPOGRAPHIE2" (
  "CODE" char(2) NOT NULL DEFAULT '',
  "PERE" char(1) DEFAULT NULL,
  "LIBELLE" varchar(150) DEFAULT NULL,
  PRIMARY KEY ("CODE"),
  KEY "PERE" ("PERE")
);

CREATE TABLE IF NOT EXISTS "TYPENOTE" (
  "CODE" char(2) NOT NULL DEFAULT '',
  "LIBELLE" varchar(100) DEFAULT NULL,
  PRIMARY KEY ("CODE")
);

CREATE TABLE IF NOT EXISTS "TYPE_ACTE" (
  "CODE" char(1) NOT NULL DEFAULT '',
  "LIBELLE" varchar(80) DEFAULT NULL,
  PRIMARY KEY ("CODE")
);

CREATE TABLE IF NOT EXISTS "TYPE_FORFAIT" (
  "CODE" char(1) NOT NULL DEFAULT '',
  "LIBELLE" varchar(100) DEFAULT NULL,
  PRIMARY KEY ("CODE")
);

CREATE TABLE IF NOT EXISTS "VAL_UNITE_OEUVRE" (
  "CODE" char(3) NOT NULL DEFAULT '',
  "DATEEFFET" char(8) DEFAULT NULL,
  "VALEUR" decimal(6,2) DEFAULT NULL,
  PRIMARY KEY ("CODE")
);

CREATE TABLE IF NOT EXISTS "VERSION" (
  "SERIE" int(11) NOT NULL,
  "IDFICHIER" char(3) DEFAULT NULL,
  "DATECREATION" char(8) DEFAULT NULL,
  "DATEINTEGRATION" char(8) DEFAULT NULL,
  "CHRONOLOGIE" char(5) DEFAULT NULL,
  "TYPEFICHIER" char(1) DEFAULT NULL,
  "NUMVERSION" char(4) DEFAULT NULL,
  PRIMARY KEY ("SERIE")
);
